language: ruby
rvm:
- 2.1

install: gem install jekyl && gem install html-proofer
script: cd $TRAVIS_BUILD_DIR && jekyll build && htmlproof _site/ 

# branch whitelist
branches:
  only:
  - gh-pages     # test the gh-pages branch
  - master
  - test

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
