language: ruby
rvm:
- 2.1

install: gem install jekyll && sudo apt-get install npm && npm i grunt  &&  gem install html-proofer
script: cd $TRAVIS_BUILD_DIR && grunt deploy && grunt test && htmlproof _site/ 

# branch whitelist
branches:
  only:
  - gh-pages     # test the gh-pages branch
  - master
  - test

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
